// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rqwshksgnnzcdfiensjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxd3Noa3Nnbm56Y2RmaWVuc2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNTk3NzEsImV4cCI6MjA3ODgzNTc3MX0.J6946fK9ZsrynWStxTdAl9zBRW5kQlYmaFDlf8WJEdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);